### ISSUE TITLE
[Highlight] error on Ubuntu 20.04

### ISSUE THREAD

**Issue by spvkgn** [shmuz/LuaFAR-2L#11]
Попробовал включить этот плагин. На 22.04 все нормально, а вот на 20.04 при запуске FAR2M такая ошибка:
```
highlight.lua:175: attempt to call method 'capturecount' (a nil value)
```
<details>
<summary>Screenshot</summary>

![Снимок экрана в 2024-05-14 17-37-43](https://github.com/shmuz/luafar2m/assets/4147135/c7a50418-aa04-4ae1-aeb2-ffb6ee0e56d7)

</details>

**Comment by shmuz** [comment]
Данная ошибка меня поставила в тупик, да настолько, что установил Ubuntu 20.04 на виртуалку и далее всё необходимое, чтобы воспроизвести проблему. Но проблема не воспроизвелась, плагин работает и подсвечивает файлы.

Теоретически, могу предположить, что luarocks установил пакет lrexlib-oniguruma для другой версии Lua, не для 5.1.

**Comment by shmuz** [comment]
> Т.е. было достаточно установить пакет apt install lua-rex-onig

А, я о таком пакете не слышал даже.

Я устанавливаю так:
`sudo apt install luarocks`
`sudo luarocks install lrexlib-oniguruma --lua-version 5.1`

**Comment by shmuz** [comment]
Это хорошо :)
Но мне кажется, не надо этот плагин устанавливать в PPA, поскольку для большинства пользователей колорер предпочтительнее.

**Comment by shmuz** [comment]
> Вроде по-умолчанию все равно colorer будет.

По моим наблюдениям - нет. Они друг о друге не знают, и оба работают. Чаще всего Highlight "побеждает"..
