### ISSUE TITLE
собрать плугины

### ISSUE THREAD

**Issue by LihacheFF** [shmuz/LuaFAR-2L#6]
Привет.
Сказано:
"How to build
Unpack this package into Plugins/luafar directory.

Edit the first line in config.mak (FARSOURCE) to point to Far2L source tree on your disk.

Execute make."
1. - сделал
2.  - FARSOURCE = $(/usr/share)/far2l
3. sudo chmod ugo+x Makefile
4. запускаю Makefile
5. вот что вижу:
/usr/share/far2l/Plugins/luafar$ ./Makefile
./Makefile: строка 3: ifdef: команда не найдена
./Makefile: строка 4: PARAM: команда не найдена
./Makefile: строка 5: endif: команда не найдена
./Makefile: строка 7: синтаксическая ошибка рядом с неожиданным маркером «$(USER),shmuel»
./Makefile: строка 7: `ifeq ($(USER),shmuel)'

что делать?

и есть ли еще вкусные плугины?

**Comment by shmuz** [comment]
Судя по картинке в телеграме, **у вас плагины уже установлены.**
Если хотите их сами собирать, надо сделать **клон моего форка far2l**, потому что `$(/usr/share)/far2l` это не исходники фара, а инсталляция.
Вкусных плагинов около десятка, но многое макросы тянут на плагины.

**Comment by shmuz** [comment]
Немного объясню, кое-что может быть неочевидным:
1. Присутствуют все плагины оригинального far2l - в папке `Plugins`
2. Дополнительные (мои) плагины находятся в папке `Plugins/luafar`
3. Макросы нужно ставить самостоятельно, и только те, которые нужны.
4. Файлы с макросами (макрофайлы) нужно класть в папку `~/.config/far2l/Macros/scripts` (эта папка создаётся Фаром автоматически).
5. Мои макросы можно брать из этой репозитории из папки `Macros/scripts`.

На случай, если вы не в курсе, Lua-макросы по возможностям равны плагинам. Вот например макрос "календарь"
![image](https://user-images.githubusercontent.com/344558/233777467-f356c057-4900-45a8-a323-e997244ecd59.png)
